FRRouting Release 7.3 Integration
1. The necessary patches which are required for this version are taken from frr-vyatta-6.0 .
2. The FRRouting version 7.3 is tested with DANOS-1908.
   a. Tested OSPF, BGP, OSPFv3 and Static.
3. The changes added in FRRouting version 7.3 are as follows.
   This below message is taken from FRRouting version 7.3 changelog.

BGPd
   EVPN PIP Support
   Route Aggregation code speed ups
   BGP Vector I/O speed ups
   New CLI: `set distance XXX`
   New CLI: `aggregate-address A.B.C.D/M route-map WORD`
   New CLI: `bgp reject-as-sets`
   New CLI: `advertise pip ...`
   New CLI: `match evpn rd ASN:NN_OR_IP-ADDRESS:NN`
   New CLI: `show bgp l2vpn evpn community|large-community X`
   New CLI: `show bgp l2vpn evpn A.B.C.D`
   Auto-completion for clear bgp command
   Add ability to set tcp socket buffer size
OSPFd
   Partial MPLS TE support
PBRd
   New CLI: `set vrf unchanged|NAME`
BFDd
   VRF Support
   New CLI: 'show bfd peers brief'
   New CLI: 'clear bfd peer ...'
PIMd
   Significant Speedups in accessing Internal Data for higher scale
   Support for joining any-source Multicast
   Updated CLI: 'show ip pim upstream-join-desired'
   New CLI: 'show ip pim channel'
   Debug Cleanup
   MLAG experimental support
VRRPd
   VRF Support
   Northbound Conversion- NHRPd
LDPd
vtysh
   New CLI: `banner motd line LINE...`
yang
   New CLI: `show yang operational-data XPATH`
   New CLI: `debug northbound`
Zebra
   Nexthop Group support
   New CLI: 'debug zebra nexthop [detail]'
   New CLI: 'show router-id'
   MLAG experimental support
watchfrr
   Additional status messages of system state to systemd
   New CLI: `watchfrr ignore DAEMON`
Others
   As always all daemons have received too many bug fixes to fully list
   There has been a significant focus on increasing test coverage
Change in Behavior:
   ISISd
      All areas created default automatically to level-1-2
   Zebra
      Nexthop Group Installation in Kernel is turned on by default
      if the kernel supports-    New CLI: 'show nexthop-group rib [singleton]'
   Man Pages
      Renamed to frr-* to remove collision with other packages

Signed-off-by: kaushik <kaushik@niralnetworks.com>

diff --git a/debian/frr.postinst b/debian/frr.postinst
--- a/debian/frr.postinst
+++ b/debian/frr.postinst
@@ -1,37 +1,96 @@
-#!/bin/bash -e
+#!/bin/sh
+set -e
 
-######################
-PASSWDFILE=/etc/passwd
-GROUPFILE=/etc/group
+# most of this file makes sense to execute regardless of whether this is any
+# of normal "configure" or error-handling "abort-upgrade", "abort-remove" or
+# "abort-deconfigure"
 
-frruid=`egrep "^frr:" $PASSWDFILE | awk -F ":" '{ print $3 }'`
-frrgid=`egrep "^frr:" $GROUPFILE | awk -F ":" '{ print $3 }'`
-frrvtygid=`egrep "^frrvty:" $GROUPFILE | awk -F ":" '{ print $3 }'`
+addgroup --system frrvty
+addgroup --system frr
+adduser \
+	--system \
+	--ingroup frr \
+	--home /nonexistent \
+	--gecos "Frr routing suite" \
+	--no-create-home \
+	frr
+usermod -a -G frrvty frr
 
-[ -n ${frruid} ]    || (echo "No uid for frr in ${PASSWDFILE}"   && /bin/false)
-[ -n ${frrgid} ]    || (echo "No gid for frr in ${GROUPFILE}"    && /bin/false)
-[ -n ${frrVTYgid} ] || (echo "No gid for frrvty in ${GROUPFILE}" && /bin/false)
+mkdir -p /var/log/frr
+mkdir -p /etc/frr
 
-chown ${frruid}:${frrgid} /etc/frr
-chown ${frruid}:${frrgid} /etc/frr/*
-touch /etc/frr/vtysh.conf
-chgrp ${frrvtygid} /etc/frr/vtysh*
-chmod 644 /etc/frr/*
 
-ENVIRONMENTFILE=/etc/environment
-if ! egrep --quiet '^VTYSH_PAGER=' ${ENVIRONMENTFILE}; then
-    echo "VTYSH_PAGER=/bin/cat"  >> ${ENVIRONMENTFILE}
-fi
-##################################################
+# only change ownership of files when they were previously owned by root or
+# quagga; this is to ensure we don't trample over some custom user setup.
+#
+# if we are on a freshly installed package (or we added new configfiles),
+# the files should be owned by root by default so we should end up with "frr"
+# owned configfiles.
 
-if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
-${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*"}
+quaggauid=`id -u quagga 2>/dev/null || echo 0`
+quaggagid=`id -g quagga 2>/dev/null || echo 0`
 
-# This is most likely due to the answer "no" to the "really stop the server"
-# question in the prerm script.
-if [ "$1" = "abort-upgrade" ]; then
-  exit 0
-fi
+find \
+	/etc/frr \
+	/var/log/frr \
+		\( -uid 0 -o -uid $quaggauid \) -a \
+		\( -gid 0 -o -gid $quaggauid \) | \
+	while read filename; do
+
+	# don't chown anything that has ACLs (but don't fail if we don't
+	# have getfacl)
+	if { getfacl -c "$filename" 2>/dev/null || true; } \
+		| egrep -q -v '^((user|group|other)::|$)'; then
+		:
+	else
+		chown frr: "$filename"
+		chmod o-rwx "$filename"
+	fi
+done
+
+# fix misconfigured vtysh.conf & frr.conf ownership caused by config save
+# mishandling in earlier FRR (and Quagga) versions
+find /etc/frr -maxdepth 1 \( -name vtysh.conf -o -name frr.conf \) \
+	-group frrvty -exec chgrp frr {} \;
+
+# more Quagga -> FRR upgrade smoothing.  Not technically needed, but let's
+# at least do the straightforward pieces.
+
+check_old_config() {
+	oldcfg="$1"
+	[ -r "$oldcfg" ] || return 0
+	[ -s "$oldcfg" ] || return 0
+	grep -v '^[[:blank:]]*\(#\|$\)' "$oldcfg" > /dev/null || return 0
+
+	cat >&2 <<EOF
+Note: deprecated $oldcfg is present. This file is still read by
+the FRR service but its contents should be migrated to /etc/frr/daemons.
+EOF
+}
+
+rmsum() {
+	fname="$1"
+	test -f "$1" || return 0
+	fhash="`sha1sum \"$fname\"`"
+	fhash="${fhash%% *}"
+	if test "$fhash" = "$2"; then
+		rm "$fname"
+	fi
+}
+
+case "$1" in
+configure)
+	check_old_config /etc/frr/daemons.conf
+	check_old_config /etc/default/frr
+	if test -f /etc/frr/.pkg.frr.nointegrated; then
+		# remove integrated config setup
+		# (if checksums match, the files match freshly installed
+		# defaults, but the user has split config in place)
+		rmsum /etc/frr/vtysh.conf 5e7e3a488c51751e1ff98f27c9ad6085e1ad9cbb
+		rmsum /etc/frr/frr.conf   dac6f2af4fca9919ba40eb338885a5d1773195c8
+		rm /etc/frr/.pkg.frr.nointegrated
+	fi
+	;;
+esac
 
 #DEBHELPER#
-
